###############################################################################
# rds module — Aurora PostgreSQL
#
# Encrypted, private (no public access), optionally multi-AZ Aurora cluster. The
# master password is generated by Terraform and stored in AWS Secrets Manager —
# it is never written to a tfvars file. The plaintext password still lands in
# state, so the remote state bucket's encryption + access controls are the real
# secret boundary.
###############################################################################

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5"
    }
  }
}

data "aws_partition" "current" {}

###############################################################################
# Networking — subnet group + security group
###############################################################################

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-aurora"
  subnet_ids = var.subnet_ids

  tags = merge(var.tags, {
    Name = "${var.name}-aurora"
  })
}

resource "aws_security_group" "this" {
  name        = "${var.name}-aurora"
  description = "Aurora PostgreSQL access for ${var.name}"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, {
    Name = "${var.name}-aurora"
  })
}

# Ingress from explicitly-allowed security groups (e.g. EKS nodes).
resource "aws_vpc_security_group_ingress_rule" "from_sg" {
  for_each = toset(var.allowed_security_group_ids)

  security_group_id            = aws_security_group.this.id
  description                  = "Postgres from ${each.value}"
  referenced_security_group_id = each.value
  from_port                    = var.port
  to_port                      = var.port
  ip_protocol                  = "tcp"
}

# Ingress from explicit CIDRs (use sparingly).
resource "aws_vpc_security_group_ingress_rule" "from_cidr" {
  for_each = toset(var.allowed_cidr_blocks)

  security_group_id = aws_security_group.this.id
  description       = "Postgres from ${each.value}"
  cidr_ipv4         = each.value
  from_port         = var.port
  to_port           = var.port
  ip_protocol       = "tcp"
}

resource "aws_vpc_security_group_egress_rule" "all" {
  security_group_id = aws_security_group.this.id
  description       = "Allow all outbound"
  cidr_ipv4         = "0.0.0.0/0"
  ip_protocol       = "-1"
}

###############################################################################
# Encryption key (storage at rest)
###############################################################################

resource "aws_kms_key" "this" {
  description             = "${var.name} Aurora storage encryption"
  deletion_window_in_days = var.kms_deletion_window_days
  enable_key_rotation     = true

  tags = merge(var.tags, {
    Name = "${var.name}-aurora-storage"
  })
}

resource "aws_kms_alias" "this" {
  name          = "alias/${var.name}-aurora-storage"
  target_key_id = aws_kms_key.this.key_id
}

###############################################################################
# Credentials — generated password stored in Secrets Manager
###############################################################################

resource "random_password" "master" {
  length = 32
  # Avoid characters that break PostgreSQL connection URIs / shell quoting.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "master" {
  name                    = "${var.name}/aurora/master"
  description             = "Master credentials for the ${var.name} Aurora cluster"
  recovery_window_in_days = var.secret_recovery_window_days
  kms_key_id              = aws_kms_key.this.arn

  tags = var.tags
}

# Store a JSON blob compatible with the RDS/Aurora secret rotation format so it
# can be consumed directly (or rotated later) without reshaping.
resource "aws_secretsmanager_secret_version" "master" {
  secret_id = aws_secretsmanager_secret.master.id
  secret_string = jsonencode({
    engine   = "postgres"
    username = var.master_username
    password = random_password.master.result
    host     = aws_rds_cluster.this.endpoint
    port     = var.port
    dbname   = var.database_name
  })
}

###############################################################################
# Enhanced monitoring role (only when monitoring is enabled)
###############################################################################

data "aws_iam_policy_document" "monitoring_assume" {
  count = var.monitoring_interval > 0 ? 1 : 0

  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "monitoring" {
  count              = var.monitoring_interval > 0 ? 1 : 0
  name               = "${var.name}-aurora-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume[0].json
  tags               = var.tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  count      = var.monitoring_interval > 0 ? 1 : 0
  role       = aws_iam_role.monitoring[0].name
  policy_arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

###############################################################################
# Aurora cluster + instances
###############################################################################

resource "aws_rds_cluster" "this" {
  cluster_identifier = "${var.name}-aurora"
  engine             = "aurora-postgresql"
  engine_version     = var.engine_version
  database_name      = var.database_name
  port               = var.port

  master_username = var.master_username
  master_password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]

  storage_encrypted = true
  kms_key_id        = aws_kms_key.this.arn

  backup_retention_period      = var.backup_retention_days
  preferred_backup_window      = var.preferred_backup_window
  preferred_maintenance_window = var.preferred_maintenance_window

  deletion_protection = var.deletion_protection
  skip_final_snapshot = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-aurora-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  # Ship Postgres logs to CloudWatch for audit/troubleshooting.
  enabled_cloudwatch_logs_exports = ["postgresql"]

  # IAM database authentication — allow IRSA-issued IAM auth to the DB.
  iam_database_authentication_enabled = true

  apply_immediately = var.apply_immediately

  tags = merge(var.tags, {
    Name = "${var.name}-aurora"
  })

  lifecycle {
    # final_snapshot_identifier uses timestamp(); ignore so it doesn't replan.
    ignore_changes = [final_snapshot_identifier]
  }
}

resource "aws_rds_cluster_instance" "this" {
  count = var.instance_count

  identifier         = "${var.name}-aurora-${count.index}"
  cluster_identifier = aws_rds_cluster.this.id
  instance_class     = var.instance_class
  engine             = aws_rds_cluster.this.engine
  engine_version     = aws_rds_cluster.this.engine_version

  db_subnet_group_name = aws_db_subnet_group.this.name

  # Never expose an Aurora instance to the public internet.
  publicly_accessible = false

  performance_insights_enabled    = var.performance_insights_enabled
  performance_insights_kms_key_id = var.performance_insights_enabled ? aws_kms_key.this.arn : null

  monitoring_interval = var.monitoring_interval
  monitoring_role_arn = var.monitoring_interval > 0 ? aws_iam_role.monitoring[0].arn : null

  apply_immediately = var.apply_immediately

  tags = merge(var.tags, {
    Name = "${var.name}-aurora-${count.index}"
    # First instance is the writer; the rest are readers.
    Role = count.index == 0 ? "writer" : "reader"
  })
}
